# Generated by Django 5.0.7 on 2024-08-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0006_alter_note_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='status',
        ),
    ]
